"""Add total_value column to portfolios

Revision ID: 152736a7917b
Revises: 74b8709e5091
Create Date: 2025-10-22 09:32:06.684493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152736a7917b'
down_revision: Union[str, Sequence[str], None] = '74b8709e5091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('total_value', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'total_value')
    # ### end Alembic commands ###
